### ISSUE TITLE
Problems in the Response of a Front-Channel Logout

### ISSUE THREAD

**Issue by gergan** [zmartzone/mod_auth_openidc#345]
###### Environment

- mod_auth_openidc-2.3.3-1.el7.centos.x86_64.rpm from github
- cjose-0.5.1-1.el7.centos.x86_64.rpm from github
- Apache/2.4.6 (CentOS) Server built:   Oct 19 2017 20:39:16
- CentOs 7 in Docker

We are using mod_auth_openidc as a Relying Party for our Microservices and the OP is keycloak-3.4.3.

We experience a strange behavior by the Front-Channel Logout - it works in almost all the browsers, except for the chrome and opera, where we experience intermittent failures. 

We bind the both iframes (OP/RP) over the redirect_uri - exactly as described in the wiki. 

The iframes determine correctly, that a logout happened and send the RP-iframe a redirect to redirect_uri?session=check, which in turn redirects the iframe to keycloaks's auth?response_type, which finally redirects the iframe to redirect_uri?error=login_required&state...

This leads to a strange intermittent problem in Chrome/Opera, sometimes it works and the browser makes the correct redirect to the logout page, sometimes it shows the error from the image (net::ERR_INCOMPLETE_CHUNKED_ENCODING).
![response_problem](https://user-images.githubusercontent.com/444543/38496835-3eb80e80-3bff-11e8-8f3d-63197041048d.png)

Chrome/Opera does not show the response for these requests at all. In firefox the responses are readable but somewhat strange as they contain 3 different pages:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Redirecting...</title>
        <script type="text/javascript">
      window.top.location.href = 'https://coreos-grow:9443/redirect_uri?session=logout';
    </script>

  </head>
  <body>
<p></p>
  </body>
</html>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Error</title>
    
  </head>
  <body>
<p>Error: <pre>Invalid Request</pre></p><p>Description: <pre>The OpenID Connect callback URL received an invalid request</pre></p>
  </body>
</html>
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 root@localhost to inform them of the time this error occurred,
and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

**Comment by zandbelt** [comment]
Do you have associated server debug logs?

**Comment by zandbelt** [comment]
In principle the logout sequence is correct up to and including the not very elegant error 500 that is returned on a "login_required" message; this should all happen in the invisible iframe and not interfere with anything

The issue you face seems to be caused by the server doing erroneous chunking, independent of (or perhaps interfering with) mod_auth_openidc. Perhaps it is possible to dig into that and check/debug the server configuration?

**Comment by zandbelt** [comment]
any update on this?

**Comment by gergan** [comment]
The configuration files are relative simple as this is still some sort of POC-Implementation, the apache httpd.conf is:
[httpd.conf.txt](https://github.com/zmartzone/mod_auth_openidc/files/2027461/httpd.conf.txt)
and the sites-configuration (minimally changed to remove credentails and such) is as follows:
[apache.conf.txt](https://github.com/zmartzone/mod_auth_openidc/files/2027470/apache.conf.txt)

I'm by no means expert in apache but I don't see any obvious error in the configs (probably some of the lines are redundant).

In the beginning I had a quick look at the relevant code portions and speculated on missing return after the following [line](https://github.com/zmartzone/mod_auth_openidc/blob/bc10367ff125b5a6f5973a04b11180331c1e40d4/src/mod_auth_openidc.c#L3230), but I didn't have the time to debug it or follow on and understand the complete logic (so I didn't mentioned it in the beginning) and it is really just a wild guess.

**Comment by zandbelt** [comment]
I think you spotted an error wrt. the missing return indeed, thanks!

**Comment by zandbelt** [comment]
Never mind: you should be able to use http://mod-auth-openidc.org/download/mod_auth_openidc-2.3.6rc1-1.el7.x86_64.rpm to confirm. At least the problem with the concatenated HTML output should be fixed. Not sure about how your application handles the iframe.

**Comment by gergan** [comment]
Thanks, I’ll test it tomorrow and report the results.

**Comment by gergan** [comment]
We have problems with our infrastructure, so I'm still unable to test the fix.
Unfortunately we have offside next week, so I'll be probably be able to give you feedback in the first june week.

**Comment by gergan** [comment]
So I have managed to test the fix and I could not reporduce the problem any more. So it seems that the fix works.
